# docker container run -itd --name webserver -e USERNAME='GAURAV' --network=test -p 8000:80 -v abc:/code nginx
version: '3.3'
services:
  redis:
    image: redis

  mysql:
    image: mysql
  webserver:
    # image: mycust #custom name if context not define.
    build: .
#      context: ./docker/ #path for docker file.
#      dockerfile: Dockerfiledev # define docker file name.
#      args:
#        PYTHON_VERSION: 3.7
#        EXPOSE_PORT: 9000
    ports: 
      - 80 #random port.
#      - 9080:80 #manual port mapping.
#      - 9000:9000
    environment:
      - username="gaurav" #env variable
    networks: 
      - test
      - test2
    volumes: 
      - ./:/code #bind mount
      - test_volume:/abc # volume mount

  python:
    image: coolgourav147/testpython
    build: 
      context: ./docker/ #path for docker file.
      dockerfile: Dockerfile # define docker file name.
      args:
        PYTHON_VERSION: 3.7
        EXPOSE_PORT: 9000
networks: 
  test: # create new network
  test2: # create new network


volumes:
  test_volume:
